
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqetqqjcmjdcnnswtgho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxZXRxcWpjbWpkY25uc3d0Z2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1OTk1MzYsImV4cCI6MjA2MDE3NTUzNn0.zmdbcpjGCGuSStBtfBbMvcs6BwZPm0jv9AiqhUrwhrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
