// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpkehspgchhtdhbfhztc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxwa2Voc3BnY2hodGRoYmZoenRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NjY5OTYsImV4cCI6MjA3NDQ0Mjk5Nn0.7VhcIm_9UgRHmx6UA2SEU6tMZuNPlxcDElUN5xcZAMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});